eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
server:
  port: 9003
spring:
  application:
    name: lechi-consumer
  datasource:
    url: jdbc:oracle:thin:@192.168.31.198:49161:xe
    driver-class-name: oracle.jdbc.OracleDriver
    username: LIUCHAOLING
    password: '@Liuchaoling123'
  #thymeleaf:
   # prefix: / #classpath:/static/  #prefix：指定模板所在的目录
    #check-template-location: true  #check-tempate-location: 检查模板路径是否存在
    #cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
    #suffix:  .html
    #encoding: UTF-8
    #content-type: text/html
    #mode: HTML5
  thymeleaf:
      prefix: classpath:/static/
      suffix: .html
      cache: false #关闭缓存